name: borra_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.6+233

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  # Services
  dio: ^5.2.1+1
  shared_preferences: ^2.0.17
  device_preview: ^1.2.0
  json_annotation: ^4.9.0
  uuid: ^3.0.7
  built_value: ">=8.4.0 <9.0.0"
  built_collection: ">=5.1.1 <6.0.0"

  # Architecture libs
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  go_router: ^10.0.0

  # Helpers
  logger: ^2.0.1
  tuple: ^2.0.1
  flutter_native_splash: ^2.2.17
  path: ^1.8.2
  flutter_screenutil: ^5.6.1
  kakao_flutter_sdk: ^1.9.2
  kakao_flutter_sdk_auth: ^1.5.0
  kakao_flutter_sdk_user: ^1.5.0
  sign_in_with_apple: ^5.0.0
  collection: ^1.17.1
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.12
  clipboard: ^0.1.3
  firebase_dynamic_links: ^5.4.3
  flutter_inappwebview: ^5.7.2+3
  home_widget: ^0.6.0
  flutter_secure_storage: ^8.0.0
  # Testing
  mockito: ^5.3.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # UI libs
  easy_localization: ^3.0.1
  another_flushbar: ^1.12.29
  shimmer: ^3.0.0
  pull_to_refresh_flutter3: ^2.0.2

  responsive_framework: ^1.1.0
  flutter_spinkit: ^5.1.0

  modal_bottom_sheet: ^2.1.2
  easy_mask: ^2.0.1
  lottie: ^2.2.0

  one_of: ">=1.5.0 <2.0.0"
  one_of_serializer: ">=1.5.0 <2.0.0"
  dropdown_button2: ^2.1.4
  local_auth: ^2.1.5
  camera: ^0.10.3+2
  device_info_plus: ^9.0.2
  flutter_svg: ^2.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flip_card: ^0.7.0
  overlapped_carousel: ^1.0.1
  # image: ^4.0.17
  flutter_html: any
  flutter_staggered_animations: ^1.1.1
  in_app_purchase: ^3.1.8
  get: ^4.6.5
  app_tracking_transparency: ^2.0.4
  app_settings: ^5.0.0
  advertising_id: ^2.4.0
  flutter_segment: ^3.13.1
  firebase_core: ^2.15.0
  firebase_remote_config: ^4.2.4
  in_app_review: ^2.0.6
  auto_size_text: ^3.0.0
  google_mobile_ads: ^4.0.0
  percent_indicator: ^4.0.1
  dart_jsonwebtoken: ^2.13.0
  number_paginator: ^0.4.1
  workmanager: ^0.5.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.1.1
  dio_smart_retry: ^6.0.0
  app_links: ^6.1.3
  scrollable_positioned_list: ^0.3.8
# dependency_overrides:
# image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^2.1.3
  test: ^1.24.9
flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/juyeog/
    - assets/translations/
  fonts:
    - family: NotoSansKR-Black
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
    - family: NotoSansKR-Bold
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.otf
    - family: NotoSansKR-Light
      fonts:
        - asset: assets/fonts/NotoSansKR-Light.otf
    - family: NotoSansKR-Medium
      fonts:
        - asset: assets/fonts/NotoSansKR-Medium.otf
    - family: NotoSansKR-Regular
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
    - family: NotoSansKR-Thin
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
    - family: Pretendard-Black
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
    - family: Pretendard-ExtraBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
    - family: Pretendard-ExtraLight
      fonts:
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
    - family: Pretendard-Light
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
    - family: Pretendard-Thin
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
