// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqxL3DpNusyvv1mePE-4Uzf31n77O2_k',
    appId: '1:887454029577:android:411256481222ab6e77e5d8',
    messagingSenderId: '887454029577',
    projectId: 'hellounse-93333',
    databaseURL: 'https://hellounse-93333.firebaseio.com',
    storageBucket: 'hellounse-93333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97ZqBk7nCX4EBZprNdg0k1cWholRHGFM',
    appId: '1:887454029577:ios:f4cbb5c6ea84577e77e5d8',
    messagingSenderId: '887454029577',
    projectId: 'hellounse-93333',
    databaseURL: 'https://hellounse-93333.firebaseio.com',
    storageBucket: 'hellounse-93333.appspot.com',
    iosClientId: '887454029577-dppg278ac7ffqmas2j4ds1lu57o1p58s.apps.googleusercontent.com',
    iosBundleId: 'com.firstmecca.hellounsemobile',
  );
}
